#ifndef CLGUI_EMBED_H
#define CLGUI_EMBED_H
static const char *clgui_embedded =
  "#include <X11/Xlib.h>\n"
  "#include <X11/Xutil.h>\n"
  "#include <X11/keysym.h>\n"
  "#include <stdlib.h>\n"
  "#include <string.h>\n"
  "#include <stdio.h>\n"
  "#include <time.h>\n"
  "#include <poll.h>\n"
  "#include <stdint.h>\n"
  "#include <math.h>\n"
  "\n"
  "/* Built-in cube model (fallback when no .obj loaded) */\n"
  "#define BUILTIN_NUM_VERTICES 8\n"
  "#define BUILTIN_NUM_TRIANGLES 12\n"
  "static const float builtin_vtx[BUILTIN_NUM_VERTICES][3] = {\n"
  "    {-1,-1,-1},{ 1,-1,-1},{ 1, 1,-1},{-1, 1,-1},\n"
  "    {-1,-1, 1},{ 1,-1, 1},{ 1, 1, 1},{-1, 1, 1}\n"
  "};\n"
  "static const int builtin_tri[BUILTIN_NUM_TRIANGLES][3] = {\n"
  "    {0,1,2},{0,2,3},{1,5,6},{1,6,2},\n"
  "    {5,4,7},{5,7,6},{4,0,3},{4,3,7},\n"
  "    {3,2,6},{3,6,7},{4,5,1},{4,1,0}\n"
  "};\n"
  "static const float builtin_norm[BUILTIN_NUM_TRIANGLES][3] = {\n"
  "    {0,0,-1},{0,0,-1},{1,0,0},{1,0,0},\n"
  "    {0,0,1},{0,0,1},{-1,0,0},{-1,0,0},\n"
  "    {0,1,0},{0,1,0},{0,-1,0},{0,-1,0}\n"
  "};\n"
  "\n"
  "#define MAX_WINS 16\n"
  "\n"
  "static Display *dpy = NULL;\n"
  "static Window wins[MAX_WINS];\n"
  "static GC gcs[MAX_WINS];\n"
  "static int win_n = 0;\n"
  "static XFontStruct *font = NULL;\n"
  "\n"
  "static int64_t ev_x = 0, ev_y = 0, ev_btn = 0, ev_key = 0;\n"
  "\n"
  "int64_t clgui_init(void) {\n"
  "    dpy = XOpenDisplay(NULL);\n"
  "    if (!dpy) return -1;\n"
  "    font = XLoadQueryFont(dpy, \"fixed\");\n"
  "    if (!font) font = XLoadQueryFont(dpy, \"6x13\");\n"
  "    return 0;\n"
  "}\n"
  "\n"
  "int64_t clgui_window(int64_t w, int64_t h) {\n"
  "    if (win_n >= MAX_WINS) return -1;\n"
  "    int scr = DefaultScreen(dpy);\n"
  "    Window ww = XCreateSimpleWindow(dpy, RootWindow(dpy, scr),\n"
  "        0, 0, w, h, 1, BlackPixel(dpy, scr), 0xEBEBEB);\n"
  "    XSelectInput(dpy, ww, ExposureMask | ButtonPressMask | KeyPressMask | StructureNotifyMask);\n"
  "    XMapWindow(dpy, ww);\n"
  "    GC g = XCreateGC(dpy, ww, 0, NULL);\n"
  "    if (font) XSetFont(dpy, g, font->fid);\n"
  "    wins[win_n] = ww;\n"
  "    gcs[win_n] = g;\n"
  "    return win_n++;\n"
  "}\n"
  "\n"
  "void clgui_title(int64_t idx, const char *title) {\n"
  "    if (idx < 0 || idx >= win_n) return;\n"
  "    XStoreName(dpy, wins[idx], title);\n"
  "}\n"
  "\n"
  "void clgui_fill(int64_t idx, int64_t x, int64_t y, int64_t w, int64_t h, int64_t color) {\n"
  "    if (idx < 0 || idx >= win_n) return;\n"
  "    XSetForeground(dpy, gcs[idx], color);\n"
  "    XFillRectangle(dpy, wins[idx], gcs[idx], x, y, w, h);\n"
  "}\n"
  "\n"
  "void clgui_draw_str(int64_t idx, int64_t x, int64_t y, const char *s) {\n"
  "    if (idx < 0 || idx >= win_n) return;\n"
  "    XSetForeground(dpy, gcs[idx], 0x000000);\n"
  "    XDrawString(dpy, wins[idx], gcs[idx], x, y, s, strlen(s));\n"
  "}\n"
  "\n"
  "void clgui_draw_int(int64_t idx, int64_t x, int64_t y, int64_t n) {\n"
  "    if (idx < 0 || idx >= win_n) return;\n"
  "    char buf[32];\n"
  "    snprintf(buf, sizeof(buf), \"%lld\", (long long)n);\n"
  "    XSetForeground(dpy, gcs[idx], 0x000000);\n"
  "    XDrawString(dpy, wins[idx], gcs[idx], x, y, buf, strlen(buf));\n"
  "}\n"
  "\n"
  "int64_t clgui_str_width(const char *s) {\n"
  "    if (!font) return 6 * strlen(s);\n"
  "    return XTextWidth(font, s, strlen(s));\n"
  "}\n"
  "\n"
  "int64_t clgui_color(int64_t r, int64_t g, int64_t b) {\n"
  "    return (r << 16) | (g << 8) | b;\n"
  "}\n"
  "\n"
  "int64_t clgui_event(int64_t idx) {\n"
  "    if (idx < 0 || idx >= win_n) return -1;\n"
  "    int fd = ConnectionNumber(dpy);\n"
  "    struct pollfd pfd = {fd, POLLIN, 0};\n"
  "    while (XPending(dpy) == 0) {\n"
  "        poll(&pfd, 1, -1);\n"
  "    }\n"
  "    XEvent e;\n"
  "    XNextEvent(dpy, &e);\n"
  "    switch (e.type) {\n"
  "    case Expose:\n"
  "        return e.xexpose.count == 0 ? 1 : 0;\n"
  "    case ButtonPress:\n"
  "        ev_x = e.xbutton.x;\n"
  "        ev_y = e.xbutton.y;\n"
  "        ev_btn = e.xbutton.button;\n"
  "        return 2;\n"
  "    case KeyPress: {\n"
  "        KeySym ks = XLookupKeysym(&e.xkey, 0);\n"
  "        ev_key = ks;\n"
  "        if (ks == XK_Escape) return -1;\n"
  "        return 3;\n"
  "    }\n"
  "    case DestroyNotify:\n"
  "        return -1;\n"
  "    default:\n"
  "        return 0;\n"
  "    }\n"
  "}\n"
  "\n"
  "int64_t clgui_ev_x(void) { return ev_x; }\n"
  "int64_t clgui_ev_y(void) { return ev_y; }\n"
  "int64_t clgui_ev_key(void) { return ev_key; }\n"
  "\n"
  "int64_t clgui_poll(int64_t idx, int64_t ms) {\n"
  "    if (idx < 0 || idx >= win_n) return -1;\n"
  "    int fd = ConnectionNumber(dpy);\n"
  "    struct pollfd pfd = {fd, POLLIN, 0};\n"
  "    while (XPending(dpy) == 0) {\n"
  "        int r = poll(&pfd, 1, (int)ms);\n"
  "        if (r <= 0) return 0;  /* timeout or error */\n"
  "    }\n"
  "    XEvent e;\n"
  "    XNextEvent(dpy, &e);\n"
  "    switch (e.type) {\n"
  "    case Expose:\n"
  "        return e.xexpose.count == 0 ? 1 : 0;\n"
  "    case ButtonPress:\n"
  "        ev_x = e.xbutton.x;\n"
  "        ev_y = e.xbutton.y;\n"
  "        ev_btn = e.xbutton.button;\n"
  "        return 2;\n"
  "    case KeyPress: {\n"
  "        KeySym ks = XLookupKeysym(&e.xkey, 0);\n"
  "        ev_key = ks;\n"
  "        if (ks == XK_Escape) return -1;\n"
  "        return 3;\n"
  "    }\n"
  "    case DestroyNotify:\n"
  "        return -1;\n"
  "    default:\n"
  "        return 0;\n"
  "    }\n"
  "}\n"
  "\n"
  "void clgui_flush(int64_t idx) {\n"
  "    (void)idx;\n"
  "    XFlush(dpy);\n"
  "}\n"
  "\n"
  "void clgui_close(int64_t idx) {\n"
  "    if (idx < 0 || idx >= win_n) return;\n"
  "    XDestroyWindow(dpy, wins[idx]);\n"
  "    XFreeGC(dpy, gcs[idx]);\n"
  "}\n"
  "\n"
  "void print_int(int64_t n) {\n"
  "    printf(\"%ld\\n\", (long)n);\n"
  "    fflush(stdout);\n"
  "}\n"
  "\n"
  "void sleep(int64_t secs) {\n"
  "    struct timespec ts = {secs, 0};\n"
  "    nanosleep(&ts, NULL);\n"
  "}\n"
  "\n"
  "void print_str(int64_t ptr, int64_t len) {\n"
  "    fwrite((void*)(intptr_t)ptr, 1, len, stdout);\n"
  "    fflush(stdout);\n"
  "}\n"
  "\n"
  "int64_t calc_expr(void) {\n"
  "    char buf[256];\n"
  "    size_t i = 0;\n"
  "    int c;\n"
  "    c = getchar();\n"
  "    if (c == EOF) exit(0);\n"
  "    ungetc(c, stdin);\n"
  "    while (i < 255 && (c = getchar()) != EOF && c != '\\n') buf[i++] = c;\n"
  "    buf[i] = 0;\n"
  "    if (i == 0) return 0;\n"
  "    char *p = buf;\n"
  "    int64_t term = 0, result = 0;\n"
  "    while (*p == ' ') p++;\n"
  "    while (*p >= '0' && *p <= '9') { term = term * 10 + (*p - '0'); p++; }\n"
  "    while (1) {\n"
  "        while (*p == ' ') p++;\n"
  "        char op = *p;\n"
  "        if (!op) break;\n"
  "        p++;\n"
  "        while (*p == ' ') p++;\n"
  "        int64_t num = 0;\n"
  "        while (*p >= '0' && *p <= '9') { num = num * 10 + (*p - '0'); p++; }\n"
  "        if (op == '+' || op == '-') {\n"
  "            result += term;\n"
  "            term = (op == '+') ? num : -num;\n"
  "        } else {\n"
  "            if (op == '*' || op == 'x' || op == 'X')\n"
  "                term *= num;\n"
  "            else if (op == ':' || op == '/')\n"
  "                term = num ? term / num : 0;\n"
  "        }\n"
  "    }\n"
  "    return result + term;\n"
  "}\n"
  "\n"
  "int64_t read_int(void) {\n"
  "    char buf[32];\n"
  "    if (!fgets(buf, sizeof(buf), stdin)) return 0;\n"
  "    return atoll(buf);\n"
  "}\n"
  "\n"
  "/* ============ 3D Engine ============ */\n"
  "\n"
  "/* ---- Dynamic model data ---- */\n"
  "static float *mdl_vert = NULL;  /* [nv * 3] original vertices (raw from OBJ) */\n"
  "static int mdl_nv = 0;\n"
  "static int (*mdl_tri)[3] = NULL; /* [nt][3] triangle vertex indices */\n"
  "static float *mdl_norm = NULL;   /* [nt * 3] pre-computed face normals */\n"
  "static float *mdl_color = NULL;  /* [nt * 3] per-triangle RGB (0-1) */\n"
  "static int mdl_nt = 0;\n"
  "\n"
  "/* ---- Renderer state ---- */\n"
  "static uint32_t *eng_fb = NULL;\n"
  "static int eng_w = 0, eng_h = 0;\n"
  "static int64_t eng_win = -1;\n"
  "static XImage *eng_img = NULL;\n"
  "\n"
  "static int eng_nv = 0, eng_nt = 0;\n"
  "static float *eng_cv = NULL;     /* centered/normalized vertices [nv*3] */\n"
  "static float *eng_xv = NULL;     /* transformed per-frame [nv*3] */\n"
  "static float *eng_xn = NULL;     /* rotated normals per-frame [nt*3] */\n"
  "static int *eng_order = NULL;    /* triangle render order [nt] */\n"
  "static float *eng_depth = NULL;  /* triangle depth [nt] */\n"
  "static float *eng_zbuf = NULL;   /* Z-buffer [w*h] for per-pixel depth test */\n"
  "\n"
  "static int64_t eng_t0 = 0;\n"
  "static int64_t eng_start_ms = 0;\n"
  "\n"
  "/* ---- CLI args ---- */\n"
  "static int saved_argc = 0;\n"
  "static char **saved_argv = NULL;\n"
  "\n"
  "static int64_t nanos(void) {\n"
  "    struct timespec ts;\n"
  "    clock_gettime(CLOCK_MONOTONIC, &ts);\n"
  "    return (int64_t)ts.tv_sec * 1000000000LL + (int64_t)ts.tv_nsec;\n"
  "}\n"
  "\n"
  "/* ---- free loaded model ---- */\n"
  "static void free_model_data(void) {\n"
  "    free(mdl_vert); mdl_vert = NULL;\n"
  "    free(mdl_tri);  mdl_tri = NULL;\n"
  "    free(mdl_norm); mdl_norm = NULL;\n"
  "    free(mdl_color); mdl_color = NULL;\n"
  "    mdl_nv = 0; mdl_nt = 0;\n"
  "}\n"
  "\n"
  "/* ---- OBJ/MTL parser ---- */\n"
  "#include <ctype.h>\n"
  "\n"
  "static int parse_obj(const char *path) {\n"
  "    FILE *f = fopen(path, \"rb\");\n"
  "    if (!f) return -1;\n"
  "\n"
  "    /* Resolve MTL path (same dir as OBJ) */\n"
  "    char mtl_dir[1024], mtl_name[256];\n"
  "    {\n"
  "        const char *slash = strrchr(path, '/');\n"
  "        if (slash) {\n"
  "            int len = (int)(slash - path);\n"
  "            if (len > 1023) len = 1023;\n"
  "            memcpy(mtl_dir, path, len); mtl_dir[len] = 0;\n"
  "        } else {\n"
  "            mtl_dir[0] = '.'; mtl_dir[1] = 0;\n"
  "        }\n"
  "    }\n"
  "\n"
  "    /* First pass: count vertices and faces */\n"
  "    int nv = 0, nf = 0;\n"
  "    {\n"
  "        char line[1024];\n"
  "        rewind(f);\n"
  "        while (fgets(line, sizeof(line), f)) {\n"
  "            char *p = line;\n"
  "            while (*p == ' ' || *p == '\\t') p++;\n"
  "            if (p[0] == 'v' && (p[1] == ' ' || p[1] == '\\t')) nv++;\n"
  "            else if (p[0] == 'f' && (p[1] == ' ' || p[1] == '\\t')) nf++;\n"
  "        }\n"
  "    }\n"
  "\n"
  "    /* Allocate */\n"
  "    float *verts = (float *)calloc(nv * 3, sizeof(float));\n"
  "    int *face_buf = (int *)malloc(nf * 12 * sizeof(int)); /* max 12 verts per face */\n"
  "    int *face_sizes = (int *)malloc(nf * sizeof(int));\n"
  "    int *face_mat = (int *)malloc(nf * sizeof(int));\n"
  "    if (!verts || !face_buf || !face_sizes || !face_mat) {\n"
  "        free(verts); free(face_buf); free(face_sizes); free(face_mat);\n"
  "        fclose(f); return -1;\n"
  "    }\n"
  "\n"
  "    /* MTL materials */\n"
  "    typedef struct { char name[256]; float r, g, b; } Mtl;\n"
  "    Mtl *mtls = NULL;\n"
  "    int nm = 0, cm = 16;\n"
  "    mtls = (Mtl *)malloc(cm * sizeof(Mtl));\n"
  "    if (!mtls) { free(verts); free(face_buf); free(face_sizes); free(face_mat); fclose(f); return -1; }\n"
  "\n"
  "    int vi = 0, fi = 0;\n"
  "    int cur_mat = -1;\n"
  "\n"
  "    rewind(f);\n"
  "    char line[1024];\n"
  "    while (fgets(line, sizeof(line), f)) {\n"
  "        char *p = line;\n"
  "        while (*p == ' ' || *p == '\\t') p++;\n"
  "        if (!*p || *p == '#' || *p == '\\n') continue;\n"
  "\n"
  "        if (p[0] == 'v' && p[1] == ' ' || p[1] == '\\t') {\n"
  "            float x, y, z;\n"
  "            if (sscanf(p + 1, \"%f %f %f\", &x, &y, &z) >= 3 && vi < nv) {\n"
  "                verts[vi*3+0] = x; verts[vi*3+1] = y; verts[vi*3+2] = z;\n"
  "                vi++;\n"
  "            }\n"
  "        } else if (p[0] == 'f' && (p[1] == ' ' || p[1] == '\\t')) {\n"
  "            int idxs[12];\n"
  "            int cnt = 0;\n"
  "            char *q = p + 1;\n"
  "            while (*q && cnt < 12) {\n"
  "                while (*q == ' ' || *q == '\\t') q++;\n"
  "                if (!*q || *q == '\\n') break;\n"
  "                int i = atoi(q);\n"
  "                if (i > 0) idxs[cnt++] = i - 1;\n"
  "                else if (i < 0 && vi > 0) idxs[cnt++] = vi + i;\n"
  "                /* skip vt and vn */\n"
  "                while (*q && *q != ' ' && *q != '\\t' && *q != '\\n') q++;\n"
  "            }\n"
  "            if (cnt >= 3 && fi < nf) {\n"
  "                int *fb = &face_buf[fi * 12];\n"
  "                for (int k = 0; k < cnt; k++) fb[k] = idxs[k];\n"
  "                face_sizes[fi] = cnt;\n"
  "                face_mat[fi] = cur_mat;\n"
  "                fi++;\n"
  "            }\n"
  "        } else if (strncmp(p, \"usemtl\", 6) == 0) {\n"
  "            p += 6;\n"
  "            while (*p == ' ' || *p == '\\t') p++;\n"
  "            char *nl = p;\n"
  "            while (*nl && *nl != '\\n' && *nl != '\\r') nl++;\n"
  "            *nl = 0;\n"
  "            /* find material */\n"
  "            cur_mat = -1;\n"
  "            for (int k = 0; k < nm; k++) {\n"
  "                if (strcmp(mtls[k].name, p) == 0) { cur_mat = k; break; }\n"
  "            }\n"
  "        } else if (strncmp(p, \"mtllib\", 6) == 0) {\n"
  "            p += 6;\n"
  "            while (*p == ' ' || *p == '\\t') p++;\n"
  "            char *nl = p;\n"
  "            while (*nl && *nl != '\\n' && *nl != '\\r') nl++;\n"
  "            *nl = 0;\n"
  "            /* Try to load MTL file */\n"
  "            char mtl_path[1024];\n"
  "            snprintf(mtl_path, sizeof(mtl_path), \"%s/%s\", mtl_dir, p);\n"
  "            FILE *mf = fopen(mtl_path, \"rb\");\n"
  "            if (!mf) continue;\n"
  "            char ml[512];\n"
  "            int cur_mtl = -1;\n"
  "            while (fgets(ml, sizeof(ml), mf)) {\n"
  "                char *mp = ml;\n"
  "                while (*mp == ' ' || *mp == '\\t') mp++;\n"
  "                if (!*mp || *mp == '#' || *mp == '\\n') continue;\n"
  "                if (strncmp(mp, \"newmtl\", 6) == 0) {\n"
  "                    mp += 6;\n"
  "                    while (*mp == ' ' || *mp == '\\t') mp++;\n"
  "                    char *mnl = mp;\n"
  "                    while (*mnl && *mnl != '\\n' && *mnl != '\\r') mnl++;\n"
  "                    *mnl = 0;\n"
  "                    if (nm >= cm) { cm *= 2; mtls = (Mtl *)realloc(mtls, cm * sizeof(Mtl)); }\n"
  "                    strncpy(mtls[nm].name, mp, 255);\n"
  "                    mtls[nm].r = 0.7f; mtls[nm].g = 0.7f; mtls[nm].b = 0.7f;\n"
  "                    cur_mtl = nm++;\n"
  "                } else if (strncmp(mp, \"Kd\", 2) == 0 && cur_mtl >= 0) {\n"
  "                    sscanf(mp + 2, \"%f %f %f\", &mtls[cur_mtl].r, &mtls[cur_mtl].g, &mtls[cur_mtl].b);\n"
  "                }\n"
  "            }\n"
  "            fclose(mf);\n"
  "        }\n"
  "    }\n"
  "    fclose(f);\n"
  "    nv = vi;\n"
  "\n"
  "    /* Triangulate faces */\n"
  "    int total_tris = 0;\n"
  "    for (int i = 0; i < fi; i++) total_tris += face_sizes[i] - 2;\n"
  "\n"
  "    int (*tris)[3] = (int (*)[3])malloc(total_tris * sizeof(int[3]));\n"
  "    float *norms = (float *)malloc(total_tris * 3 * sizeof(float));\n"
  "    float *colors = (float *)malloc(total_tris * 3 * sizeof(float));\n"
  "    if (!tris || !norms || !colors) {\n"
  "        free(verts); free(face_buf); free(face_sizes); free(face_mat);\n"
  "        free(tris); free(norms); free(colors); free(mtls);\n"
  "        fclose(f); return -1;\n"
  "    }\n"
  "\n"
  "    int ti = 0;\n"
  "    for (int i = 0; i < fi; i++) {\n"
  "        int *fb = &face_buf[i * 12];\n"
  "        int sz = face_sizes[i];\n"
  "        int mi = face_mat[i];\n"
  "        float mr = 0.7f, mg = 0.7f, mb = 0.7f;\n"
  "        if (mi >= 0 && mi < nm) { mr = mtls[mi].r; mg = mtls[mi].g; mb = mtls[mi].b; }\n"
  "        for (int k = 1; k < sz - 1; k++) {\n"
  "            int i0 = fb[0], i1 = fb[k], i2 = fb[k + 1];\n"
  "            if (i0 >= nv || i1 >= nv || i2 >= nv) continue;\n"
  "            tris[ti][0] = i0; tris[ti][1] = i1; tris[ti][2] = i2;\n"
  "            /* face normal */\n"
  "            float ax = verts[i1*3+0] - verts[i0*3+0];\n"
  "            float ay = verts[i1*3+1] - verts[i0*3+1];\n"
  "            float az = verts[i1*3+2] - verts[i0*3+2];\n"
  "            float bx = verts[i2*3+0] - verts[i0*3+0];\n"
  "            float by = verts[i2*3+1] - verts[i0*3+1];\n"
  "            float bz = verts[i2*3+2] - verts[i0*3+2];\n"
  "            float nx = ay*bz - az*by;\n"
  "            float ny = az*bx - ax*bz;\n"
  "            float nz = ax*by - ay*bx;\n"
  "            float len = sqrtf(nx*nx + ny*ny + nz*nz);\n"
  "            if (len > 0) { nx /= len; ny /= len; nz /= len; }\n"
  "            norms[ti*3+0] = nx; norms[ti*3+1] = ny; norms[ti*3+2] = nz;\n"
  "            colors[ti*3+0] = mr; colors[ti*3+1] = mg; colors[ti*3+2] = mb;\n"
  "            ti++;\n"
  "        }\n"
  "    }\n"
  "    total_tris = ti;\n"
  "\n"
  "    free(face_buf); free(face_sizes); free(face_mat); free(mtls);\n"
  "\n"
  "    /* Store in global model */\n"
  "    free_model_data();\n"
  "    mdl_vert = verts; mdl_nv = nv;\n"
  "    mdl_tri = tris; mdl_nt = total_tris;\n"
  "    mdl_norm = norms; mdl_color = colors;\n"
  "    return 0;\n"
  "}\n"
  "\n"
  "/* ---- Setup model centering & allocate render buffers ---- */\n"
  "void renderer_free(void); /* forward decl */\n"
  "static int setup_model(void) {\n"
  "    if (mdl_nv == 0 || mdl_nt == 0) return -1;\n"
  "\n"
  "    /* Compute centroid and scale from vertices (or builtin_vtx if embedded) */\n"
  "    float cx = 0, cy = 0, cz = 0;\n"
  "    int use_builtin = (mdl_vert == NULL);\n"
  "    for (int i = 0; i < mdl_nv; i++) {\n"
  "        float x = use_builtin ? builtin_vtx[i][0] : mdl_vert[i*3+0];\n"
  "        float y = use_builtin ? builtin_vtx[i][1] : mdl_vert[i*3+1];\n"
  "        float z = use_builtin ? builtin_vtx[i][2] : mdl_vert[i*3+2];\n"
  "        cx += x; cy += y; cz += z;\n"
  "    }\n"
  "    cx /= mdl_nv; cy /= mdl_nv; cz /= mdl_nv;\n"
  "    float max_r = 0;\n"
  "    for (int i = 0; i < mdl_nv; i++) {\n"
  "        float x = use_builtin ? builtin_vtx[i][0] : mdl_vert[i*3+0];\n"
  "        float y = use_builtin ? builtin_vtx[i][1] : mdl_vert[i*3+1];\n"
  "        float z = use_builtin ? builtin_vtx[i][2] : mdl_vert[i*3+2];\n"
  "        float dx = x - cx, dy = y - cy, dz = z - cz;\n"
  "        float r = dx*dx + dy*dy + dz*dz;\n"
  "        if (r > max_r) max_r = r;\n"
  "    }\n"
  "    float scale = sqrtf(max_r);\n"
  "    if (scale < 0.001f) scale = 1;\n"
  "\n"
  "    /* Free old centered vertices if any */\n"
  "    free(eng_cv); eng_cv = NULL;\n"
  "    free(eng_xv); eng_xv = NULL;\n"
  "    free(eng_xn); eng_xn = NULL;\n"
  "    free(eng_order); eng_order = NULL;\n"
  "    free(eng_depth); eng_depth = NULL;\n"
  "\n"
  "    eng_nv = mdl_nv;\n"
  "    eng_nt = mdl_nt;\n"
  "\n"
  "    eng_cv = (float *)malloc(eng_nv * 3 * sizeof(float));\n"
  "    eng_xv = (float *)malloc(eng_nv * 3 * sizeof(float));\n"
  "    eng_xn = (float *)malloc(eng_nt * 3 * sizeof(float));\n"
  "    eng_order = (int *)malloc(eng_nt * sizeof(int));\n"
  "    eng_depth = (float *)malloc(eng_nt * sizeof(float));\n"
  "    if (!eng_cv || !eng_xv || !eng_xn || !eng_order || !eng_depth) {\n"
  "        renderer_free(); return -1;\n"
  "    }\n"
  "\n"
  "    for (int i = 0; i < eng_nv; i++) {\n"
  "        float x = use_builtin ? builtin_vtx[i][0] : mdl_vert[i*3+0];\n"
  "        float y = use_builtin ? builtin_vtx[i][1] : mdl_vert[i*3+1];\n"
  "        float z = use_builtin ? builtin_vtx[i][2] : mdl_vert[i*3+2];\n"
  "        eng_cv[i*3+0] = (x - cx) / scale;\n"
  "        eng_cv[i*3+1] = (y - cy) / scale;\n"
  "        eng_cv[i*3+2] = (z - cz) / scale;\n"
  "    }\n"
  "    for (int i = 0; i < eng_nt; i++) eng_order[i] = i;\n"
  "    return 0;\n"
  "}\n"
  "\n"
  "/* ---- Public API ---- */\n"
  "\n"
  "int64_t renderer_init(int64_t win_idx, int64_t w, int64_t h) {\n"
  "    eng_win = win_idx;\n"
  "    eng_w = (int)w;\n"
  "    eng_h = (int)h;\n"
  "\n"
  "    eng_fb = (uint32_t *)malloc(eng_w * eng_h * sizeof(uint32_t));\n"
  "    if (!eng_fb) return -1;\n"
  "\n"
  "    eng_zbuf = (float *)malloc(eng_w * eng_h * sizeof(float));\n"
  "    if (!eng_zbuf) { free(eng_fb); eng_fb = NULL; return -1; }\n"
  "\n"
  "    int scr = DefaultScreen(dpy);\n"
  "    eng_img = XCreateImage(dpy, DefaultVisual(dpy, scr), 24, ZPixmap,\n"
  "                           0, (char*)eng_fb, eng_w, eng_h, 32, 0);\n"
  "    if (!eng_img) { renderer_free(); return -1; }\n"
  "\n"
  "    /* Use embedded Apple model by default */\n"
  "    free_model_data();\n"
  "    mdl_vert = NULL;\n"
  "    mdl_nv = BUILTIN_NUM_VERTICES;\n"
  "    mdl_nt = BUILTIN_NUM_TRIANGLES;\n"
  "    mdl_tri = NULL;\n"
  "    mdl_norm = NULL;\n"
  "    mdl_color = NULL;\n"
  "\n"
  "    if (setup_model() != 0) { renderer_free(); return -1; }\n"
  "    eng_t0 = nanos();\n"
  "    return 0;\n"
  "}\n"
  "\n"
  "int64_t renderer_load_obj(int64_t win_idx, int64_t w, int64_t h, int64_t path_ptr) {\n"
  "    eng_win = win_idx;\n"
  "    eng_w = (int)w;\n"
  "    eng_h = (int)h;\n"
  "\n"
  "    /* Allocate framebuffer if not yet */\n"
  "    if (!eng_fb) {\n"
  "        eng_fb = (uint32_t *)malloc(eng_w * eng_h * sizeof(uint32_t));\n"
  "        if (!eng_fb) return -1;\n"
  "        eng_zbuf = (float *)malloc(eng_w * eng_h * sizeof(float));\n"
  "        if (!eng_zbuf) { free(eng_fb); eng_fb = NULL; return -1; }\n"
  "        int scr = DefaultScreen(dpy);\n"
  "        eng_img = XCreateImage(dpy, DefaultVisual(dpy, scr), 24, ZPixmap,\n"
  "                               0, (char*)eng_fb, eng_w, eng_h, 32, 0);\n"
  "        if (!eng_img) { renderer_free(); return -1; }\n"
  "    }\n"
  "\n"
  "    const char *path = (const char *)(intptr_t)path_ptr;\n"
  "    if (parse_obj(path) != 0) return -1;\n"
  "    if (setup_model() != 0) { renderer_free(); return -1; }\n"
  "    eng_t0 = nanos();\n"
  "    return 0;\n"
  "}\n"
  "\n"
  "void renderer_free(void) {\n"
  "    if (eng_img) { eng_img->data = NULL; XDestroyImage(eng_img); eng_img = NULL; }\n"
  "    free(eng_fb); eng_fb = NULL;\n"
  "    free(eng_zbuf); eng_zbuf = NULL;\n"
  "    free(eng_cv); eng_cv = NULL;\n"
  "    free(eng_xv); eng_xv = NULL;\n"
  "    free(eng_xn); eng_xn = NULL;\n"
  "    free(eng_order); eng_order = NULL;\n"
  "    free(eng_depth); eng_depth = NULL;\n"
  "    free_model_data();\n"
  "    eng_nv = 0; eng_nt = 0; eng_w = 0; eng_h = 0;\n"
  "}\n"
  "\n"
  "static void rotate(double angle_y) {\n"
  "    float s = (float)sin(angle_y * M_PI / 180.0);\n"
  "    float c = (float)cos(angle_y * M_PI / 180.0);\n"
  "    for (int i = 0; i < eng_nv; i++) {\n"
  "        float x = eng_cv[i*3+0], y = eng_cv[i*3+1], z = eng_cv[i*3+2];\n"
  "        eng_xv[i*3+0] = x*c + z*s;\n"
  "        eng_xv[i*3+1] = y;\n"
  "        eng_xv[i*3+2] = -x*s + z*c;\n"
  "    }\n"
  "    for (int i = 0; i < eng_nt; i++) {\n"
  "        float nx, ny, nz;\n"
  "        if (mdl_norm) {\n"
  "            nx = mdl_norm[i*3+0]; ny = mdl_norm[i*3+1]; nz = mdl_norm[i*3+2];\n"
  "        } else {\n"
  "            nx = builtin_norm[i][0]; ny = builtin_norm[i][1]; nz = builtin_norm[i][2];\n"
  "        }\n"
  "        eng_xn[i*3+0] = nx*c + nz*s;\n"
  "        eng_xn[i*3+1] = ny;\n"
  "        eng_xn[i*3+2] = -nx*s + nz*c;\n"
  "    }\n"
  "}\n"
  "\n"
  "static void project(void) {\n"
  "    float focal = 1.732f;\n"
  "    float cam_dist = 3.0f;\n"
  "    float hw = eng_w * 0.5f, hh = eng_h * 0.5f;\n"
  "    for (int i = 0; i < eng_nv; i++) {\n"
  "        float x = eng_xv[i*3+0], y = eng_xv[i*3+1], z = eng_xv[i*3+2];\n"
  "        float zv = z + cam_dist;\n"
  "        if (zv < 0.1f) zv = 0.1f;\n"
  "        eng_xv[i*3+0] = (x * focal / zv) * hw + hw;\n"
  "        eng_xv[i*3+1] = (-y * focal / zv) * hh + hh;\n"
  "        eng_xv[i*3+2] = zv;\n"
  "    }\n"
  "}\n"
  "\n"
  "static void sort_triangles(void) {\n"
  "    for (int i = 0; i < eng_nt; i++) {\n"
  "        const int *t;\n"
  "        if (mdl_tri) t = mdl_tri[i];\n"
  "        else t = builtin_tri[i];\n"
  "        eng_depth[i] = (eng_xv[t[0]*3+2] + eng_xv[t[1]*3+2] + eng_xv[t[2]*3+2]) * 0.333333f;\n"
  "    }\n"
  "    for (int i = 1; i < eng_nt; i++) {\n"
  "        int key = eng_order[i];\n"
  "        float kd = eng_depth[key];\n"
  "        int j = i - 1;\n"
  "        while (j >= 0 && eng_depth[eng_order[j]] < kd) { eng_order[j+1] = eng_order[j]; j--; }\n"
  "        eng_order[j+1] = key;\n"
  "    }\n"
  "}\n"
  "\n"
  "/* Depth comparator for qsort (descending for painter's algorithm fallback) */\n"
  "static int tri_depth_desc(const void *a, const void *b) {\n"
  "    int ia = *(const int *)a, ib = *(const int *)b;\n"
  "    float da = eng_depth[ia], db = eng_depth[ib];\n"
  "    return (da > db) ? -1 : (da < db) ? 1 : 0;\n"
  "}\n"
  "\n"
  "static void draw_triangle(int ti) {\n"
  "    const int *t;\n"
  "    float *col;\n"
  "    if (mdl_tri) {\n"
  "        t = mdl_tri[ti];\n"
  "        col = &mdl_color[ti * 3];\n"
  "    } else {\n"
  "        t = builtin_tri[ti];\n"
  "        col = NULL;\n"
  "    }\n"
  "    /* Read projected coords and 1/camera-z for perspective-correct depth */\n"
  "    float v[3][3]; /* [vertex][x=0,y=1,z=1/z] */\n"
  "    for (int k = 0; k < 3; k++) {\n"
  "        v[k][0] = eng_xv[t[k]*3+0];\n"
  "        v[k][1] = eng_xv[t[k]*3+1];\n"
  "        v[k][2] = 1.0f / eng_xv[t[k]*3+2];\n"
  "    }\n"
  "\n"
  "    /* Back-face culling: screen-space area */\n"
  "    if ((v[1][0]-v[0][0])*(v[2][1]-v[0][1]) - (v[2][0]-v[0][0])*(v[1][1]-v[0][1]) <= 0) return;\n"
  "\n"
  "    float nx = eng_xn[ti*3+0], ny = eng_xn[ti*3+1], nz = eng_xn[ti*3+2];\n"
  "    float lx = 0.3f, ly = 0.8f, lz = 0.5f;\n"
  "    float ll = sqrtf(lx*lx + ly*ly + lz*lz);\n"
  "    lx /= ll; ly /= ll; lz /= ll;\n"
  "    float diff = nx*lx + ny*ly + nz*lz;\n"
  "    if (diff < 0) diff = 0;\n"
  "    float bright = 0.15f + 0.85f * diff;\n"
  "\n"
  "    float base_r = 0.7f, base_g = 0.7f, base_b = 0.7f;\n"
  "    if (col) { base_r = col[0]; base_g = col[1]; base_b = col[2]; }\n"
  "    else     { base_r = 180.0f/255; base_g = 40.0f/255; base_b = 40.0f/255; }\n"
  "\n"
  "    int r = (int)(base_r * 255 * bright); if (r > 255) r = 255;\n"
  "    int g = (int)(base_g * 255 * bright); if (g > 255) g = 255;\n"
  "    int b = (int)(base_b * 255 * bright); if (b > 255) b = 255;\n"
  "    uint32_t color = (r << 16) | (g << 8) | b;\n"
  "\n"
  "    /* Sort vertices by Y */\n"
  "    int vi[3] = {0, 1, 2};\n"
  "    for (int i = 0; i < 2; i++)\n"
  "        for (int j = 0; j < 2-i; j++)\n"
  "            if (v[vi[j]][1] > v[vi[j+1]][1]) { int tmp = vi[j]; vi[j] = vi[j+1]; vi[j+1] = tmp; }\n"
  "\n"
  "    /* Reorder into vx[],vy[],vz[] sorted by Y */\n"
  "    float vx[3], vy[3], vz[3];\n"
  "    for (int k = 0; k < 3; k++) {\n"
  "        vx[k] = v[vi[k]][0];\n"
  "        vy[k] = v[vi[k]][1];\n"
  "        vz[k] = v[vi[k]][2];\n"
  "    }\n"
  "\n"
  "    int y0i = (int)vy[0], y1i = (int)vy[1], y2i = (int)vy[2];\n"
  "    if (y0i < 0) y0i = 0;\n"
  "    if (y2i >= eng_h) y2i = eng_h - 1;\n"
  "    if (y0i >= eng_h || y2i < 0) return;\n"
  "\n"
  "    float dx20 = vx[2] - vx[0], dy20 = vy[2] - vy[0];\n"
  "    float dx10 = vx[1] - vx[0], dy10 = vy[1] - vy[0];\n"
  "    float dx21 = vx[2] - vx[1], dy21 = vy[2] - vy[1];\n"
  "    float dz20 = vz[2] - vz[0];\n"
  "    float dz10 = vz[1] - vz[0];\n"
  "    float dz21 = vz[2] - vz[1];\n"
  "\n"
  "    for (int y = y0i; y <= y2i; y++) {\n"
  "        float fy = (float)y + 0.5f;\n"
  "        float xl, xr, zl, zr;\n"
  "        if (y < y1i) {\n"
  "            float t20 = dy20 != 0 ? (fy - vy[0]) / dy20 : 0;\n"
  "            float t10 = dy10 != 0 ? (fy - vy[0]) / dy10 : 0;\n"
  "            xl = vx[0] + t20 * dx20;\n"
  "            xr = vx[0] + t10 * dx10;\n"
  "            zl = vz[0] + t20 * dz20;\n"
  "            zr = vz[0] + t10 * dz10;\n"
  "        } else {\n"
  "            float t20 = dy20 != 0 ? (fy - vy[0]) / dy20 : 0;\n"
  "            float t21 = dy21 != 0 ? (fy - vy[1]) / dy21 : 0;\n"
  "            xl = vx[0] + t20 * dx20;\n"
  "            xr = vx[1] + t21 * dx21;\n"
  "            zl = vz[0] + t20 * dz20;\n"
  "            zr = vz[1] + t21 * dz21;\n"
  "        }\n"
  "        if (xl > xr) {\n"
  "            float tmp = xl; xl = xr; xr = tmp;\n"
  "            tmp = zl; zl = zr; zr = tmp;\n"
  "        }\n"
  "\n"
  "        /* Use (int) truncation so pixels at shared edges are always covered\n"
  "         * by both adjacent triangles. Z-buffer resolves the overlap harmlessly. */\n"
  "        int xli = (int)xl;\n"
  "        int xri = (int)xr;\n"
  "        if (xli < 0) xli = 0;\n"
  "        if (xri >= eng_w) xri = eng_w - 1;\n"
  "        if (xli > xri) continue;\n"
  "\n"
  "        uint32_t *row = &eng_fb[y * eng_w];\n"
  "        float *zrow = &eng_zbuf[y * eng_w];\n"
  "        float dx = xr - xl;\n"
  "        if (xli == xri) {\n"
  "            /* Single pixel — sample at its center */\n"
  "            float t = (xli + 0.5f - xl) / dx;\n"
  "            float iz = zl + (zr - zl) * t;\n"
  "            if (iz >= zrow[xli]) { zrow[xli] = iz; row[xli] = color; }\n"
  "        } else {\n"
  "            for (int x = xli; x <= xri; x++) {\n"
  "                float t = (x + 0.5f - xl) / dx;\n"
  "                float iz = zl + (zr - zl) * t;\n"
  "                if (iz >= zrow[x]) { zrow[x] = iz; row[x] = color; }\n"
  "            }\n"
  "        }\n"
  "    }\n"
  "}\n"
  "\n"
  "int64_t renderer_frame(int64_t win_idx) {\n"
  "    (void)win_idx;\n"
  "    int64_t now = nanos();\n"
  "    double angle_y = fmod((double)(now - eng_t0) / 1.0e9 * 30.0, 360.0);\n"
  "\n"
  "    /* Clear framebuffer and Z-buffer (0 = infinitely far in 1/z space) */\n"
  "    int npix = eng_w * eng_h;\n"
  "    for (int i = 0; i < npix; i++) {\n"
  "        eng_fb[i] = 0x1a1a2e;\n"
  "        eng_zbuf[i] = 0.0f;\n"
  "    }\n"
  "    rotate(angle_y);\n"
  "    project();\n"
  "    for (int i = 0; i < eng_nt; i++) draw_triangle(i);\n"
  "    XPutImage(dpy, wins[eng_win], gcs[eng_win], eng_img, 0, 0, 0, 0, eng_w, eng_h);\n"
  "    XFlush(dpy);\n"
  "    return 0;\n"
  "}\n"
  "\n"
  "/* ---- CLI argument support ---- */\n"
  "int64_t clgui_argc(void) { return saved_argc; }\n"
  "int64_t clgui_argv(int64_t n) {\n"
  "    if (n < 0 || n >= saved_argc) return 0;\n"
  "    return (int64_t)(intptr_t)saved_argv[n];\n"
  "}\n"
  "\n"
  "/* wrapper main() that captures args then calls Clean's main */\n"
  "int clean_main(void);\n"
  "int main(int argc, char **argv) {\n"
  "    saved_argc = argc;\n"
  "    saved_argv = argv;\n"
  "    return clean_main();\n"
  "}\n"
  "\n"
;
#endif
